set -x
export FLASH_ATTENTION_SKIP_CUDA_CHECK=TRUE
export DISABLE_FLASH_ATTN=1
export PYTHONUNBUFFERED=1

python3 -m verl.trainer.main_ppo \
  algorithm.adv_estimator=grpo \
  data.train_files=/data/alexl/gsm8k/train.parquet \
  data.val_files=/data/alexl/gsm8k/test.parquet \
  data.train_batch_size=512 \
  data.max_prompt_length=512 \
  data.max_response_length=512 \
  data.filter_overlong_prompts=True \
  data.truncation='error' \
  actor_rollout_ref.model.path=Qwen/Qwen3-4B \
  actor_rollout_ref.model.enable_gradient_checkpointing=True \
  actor_rollout_ref.actor.optim.lr=5e-6 \
  actor_rollout_ref.actor.ppo_mini_batch_size=64 \
  actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=16 \
  actor_rollout_ref.actor.use_kl_loss=True \
  actor_rollout_ref.actor.kl_loss_coef=0.001 \
  actor_rollout_ref.actor.entropy_coeff=0 \
  actor_rollout_ref.ref.model.path=Qwen/Qwen3-4B \
  actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=16 \
  actor_rollout_ref.rollout.name=vllm \
  actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
  actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
  actor_rollout_ref.rollout.n=3 \
  algorithm.use_kl_in_reward=False \
  trainer.critic_warmup=0 \
  trainer.total_epochs=10 \
  trainer.n_gpus_per_node=2 \
  trainer.nnodes=1 \
  trainer.save_freq=1 \
  trainer.test_freq=1 \
  trainer.logger=['console','tensorboard'] \
  trainer.project_name='verl_grpo_gsm8k' \
  trainer.experiment_name='qwen3_4b_grpo' \
$@
